name: eve2ev
description: Electric Vehicle Dashboard with Energy Trading

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1
  geolocator: ^10.1.0
  flutter_map: ^6.1.1
  latlong2: ^0.9.0
  http: ^1.1.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.35.3
  permission_handler: ^11.4.0
  flutter_polyline_points: ^2.1.0
  intl: ^0.18.1
  vector_math: ^2.1.4 # For animation transformations
  flutter_svg: ^2.0.0+1
  flutter_animate: ^4.1.1+1
  supabase_flutter: ^2.3.0
  google_sign_in: ^6.1.5
  intl_phone_field: ^3.1.0
  cupertino_battery_indicator: ^1.0.0
  
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  