// lib/providers/blockchain_provider.dart
//
// Sits between the UI and WalletService/EnergyEscrow contract.
// Exposes clean async methods that the UI calls, handles loading/error state,
// and syncs trade status back to Supabase so the rest of the app stays updated.
//
import 'dart:async';
import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:web3dart/web3dart.dart';
import '../services/wallet_service.dart';

// ── Contract ABI (only the functions we call from Flutter) ───────────────────
// Full ABI generated by Hardhat/Remix after deployment — paste here.
const String _escrowAbi = '''[
  {
    "inputs": [
      {"name":"seller","type":"address"},
      {"name":"energyKwh","type":"uint256"},
      {"name":"pricePerKwh","type":"uint256"},
      {"name":"supabaseTradeId","type":"string"}
    ],
    "name": "deposit",
    "outputs": [{"name":"tradeId","type":"bytes32"}],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [{"name":"tradeId","type":"bytes32"}],
    "name": "confirmDelivery",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"name":"tradeId","type":"bytes32"}],
    "name": "confirmReceipt",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"name":"tradeId","type":"bytes32"}],
    "name": "raiseDispute",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"name":"tradeId","type":"bytes32"}],
    "name": "refund",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [{"name":"tradeId","type":"bytes32"}],
    "name": "getTrade",
    "outputs": [
      {
        "components": [
          {"name":"buyer","type":"address"},
          {"name":"seller","type":"address"},
          {"name":"amount","type":"uint256"},
          {"name":"energyKwh","type":"uint256"},
          {"name":"pricePerKwh","type":"uint256"},
          {"name":"createdAt","type":"uint256"},
          {"name":"confirmedAt","type":"uint256"},
          {"name":"status","type":"uint8"},
          {"name":"supabaseTradeId","type":"string"}
        ],
        "name":"",
        "type":"tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [{"name":"tradeId","type":"bytes32"}],
    "name": "getTradeStatus",
    "outputs": [{"name":"","type":"uint8"}],
    "stateMutability": "view",
    "type": "function"
  }
]''';

// ── Trade status enum mirroring the contract ──────────────────────────────────
enum EscrowStatus { pending, delivered, completed, disputed, refunded }

EscrowStatus _statusFromInt(int i) {
  switch (i) {
    case 0: return EscrowStatus.pending;
    case 1: return EscrowStatus.delivered;
    case 2: return EscrowStatus.completed;
    case 3: return EscrowStatus.disputed;
    case 4: return EscrowStatus.refunded;
    default: return EscrowStatus.pending;
  }
}

// ── Data class for a single on-chain trade ────────────────────────────────────
class EscrowTrade {
  final String tradeId;         // bytes32 as hex string
  final String supabaseTradeId; // energy_requests.id
  final String buyerAddress;
  final String sellerAddress;
  final double amountPol;       // human-readable POL
  final double energyKwh;
  final EscrowStatus status;
  final DateTime createdAt;

  const EscrowTrade({
    required this.tradeId,
    required this.supabaseTradeId,
    required this.buyerAddress,
    required this.sellerAddress,
    required this.amountPol,
    required this.energyKwh,
    required this.status,
    required this.createdAt,
  });
}

// ── Provider ──────────────────────────────────────────────────────────────────
class BlockchainProvider with ChangeNotifier {
  final WalletService _wallet = WalletService();
  final SupabaseClient _supabase = Supabase.instance.client;

  // ── State ──────────────────────────────────────────────────────────────────
  bool _isInitializing = false;
  bool _isProcessing = false;
  String? _errorMessage;
  String? _walletAddress;
  double _polBalance = 0.0;
  double? _polToZarRate;        // live POL→ZAR rate from CoinGecko
  final List<EscrowTrade> _trades = [];
  Timer? _balancePollTimer;

  DeployedContract? _contract;

  // ── Getters ────────────────────────────────────────────────────────────────
  bool get isInitializing => _isInitializing;
  bool get isProcessing => _isProcessing;
  String? get errorMessage => _errorMessage;
  String? get walletAddress => _walletAddress;
  double get polBalance => _polBalance;
  double? get polToZarRate => _polToZarRate;

  // ── Account management ──────────────────────────────────────────────────────

  Future<List<Map<String, String>>> getSavedAccounts() =>
      _wallet.getSavedAccounts();

  Future<bool> switchAccount(int index) async {
    final success = await _wallet.switchToAccount(index);
    if (success) {
      _walletAddress = _wallet.publicAddress;
      _polBalance = 0.0;
      notifyListeners();
      // Refresh balance for new account
      await refreshBalance();
    }
    return success;
  }
  List<EscrowTrade> get trades => List.unmodifiable(_trades);
  bool get walletReady => _walletAddress != null;

  bool _isFirstLaunch = false;
  bool get isFirstLaunch => _isFirstLaunch;

  /// Call this before initialize() to detect first launch without creating a wallet.
  Future<void> checkFirstLaunch() async {
    final exists = await _wallet.hasExistingWallet();
    _isFirstLaunch = !exists;
    notifyListeners();
  }

  /// Exposed so WalletScreen can call getMnemonic() without a separate service lookup
  WalletService get walletServiceRef => _wallet;

  // ── Init ───────────────────────────────────────────────────────────────────

  /// Creates a brand new wallet then fully initializes.
  Future<void> createAndInitialize() async {
    await _wallet.createNewWalletPublic();
    _isFirstLaunch = false;
    await initialize();
  }

  Future<void> initialize() async {
    if (_isInitializing || walletReady) return;
    _isInitializing = true;
    _errorMessage = null;
    notifyListeners();

    try {
      await _wallet.initialize();
      _walletAddress = _wallet.publicAddress;

      // Save wallet address to Supabase user profile so sellers can be paid
      await _syncWalletAddressToSupabase();

      // Set up contract handle
      _contract = DeployedContract(
        ContractAbi.fromJson(_escrowAbi, 'EnergyEscrow'),
        EthereumAddress.fromHex(WalletService.contractAddress),
      );

      // Fetch initial balance
      _polBalance = await _wallet.getBalance();

      debugPrint('✅ BlockchainProvider initialized: $_walletAddress');
      _startBalancePolling();
    } catch (e) {
      _errorMessage = 'Wallet initialization failed: $e';
      debugPrint('❌ BlockchainProvider init error: $e');
    } finally {
      _isInitializing = false;
      notifyListeners();
    }
  }

  Future<void> refreshBalance() async {
    if (!walletReady) return;
    _polBalance = await _wallet.getBalance();
    notifyListeners();
  }

  Future<void> _syncWalletAddressToSupabase() async {
    try {
      final userId = _supabase.auth.currentUser?.id;
      if (userId == null || _walletAddress == null) return;

      await _supabase
          .from('profiles')                        // base table, not the view
          .upsert({'user_id': userId, 'wallet_address': _walletAddress},
              onConflict: 'user_id');

      debugPrint('✅ Wallet address synced to Supabase');
    } catch (e) {
      debugPrint('⚠️ Could not sync wallet address: $e');
    }
  }

  // ── Contract call helpers ──────────────────────────────────────────────────

  ContractFunction _fn(String name) => _contract!.function(name);

  // ── Core trade actions ─────────────────────────────────────────────────────

  /// Buyer deposits POL into escrow for an accepted energy request.
  ///
  /// [supabaseRequestId] — energy_requests.id from Supabase
  /// [sellerWalletAddress] — seller's on-chain address (from user_profiles)
  /// [energyKwh] — amount of energy being purchased
  /// [totalPol] — total POL to lock (energy × price converted to POL)
  ///
  /// Returns the on-chain tradeId (bytes32 hex) on success, null on failure.
  Future<String?> depositToEscrow({
    required String supabaseRequestId,
    required String sellerWalletAddress,
    required double energyKwh,
    required double totalPol,
  }) async {
    if (!_assertReady()) return null;

    _setProcessing(true);
    try {
      // Convert values to contract-expected units
      final energyMilliKwh = BigInt.from((energyKwh * 1000).round());
      final pricePerKwh = BigInt.from(1); // placeholder — price is in totalPol
      final valueWei = EtherAmount.fromBase10String(
        EtherUnit.ether,
        totalPol.toStringAsFixed(18),
      ).getInWei;

      // Encode deposit() call data
      final data = _fn('deposit').encodeCall([
        EthereumAddress.fromHex(sellerWalletAddress),
        energyMilliKwh,
        pricePerKwh,
        supabaseRequestId,
      ]);

      final txHash = await _wallet.sendTransaction(
        toAddress: WalletService.contractAddress,
        valueWei: valueWei,
        data: Uint8List.fromList(data),
      );

      debugPrint('📤 deposit() tx: $txHash');

      // Wait for mining
      final receipt = await _wallet.waitForReceipt(txHash);
      if (receipt == null || !receipt.status!) {
        throw Exception('Transaction failed on-chain');
      }

      // Extract tradeId from event logs (first topic of TradeCreated)
      final tradeId = _extractTradeIdFromReceipt(receipt);

      // Record in Supabase
      await _recordTxInSupabase(
        requestId: supabaseRequestId,
        txHash: txHash,
        tradeId: tradeId,
        action: 'deposit',
        amountPol: totalPol,
      );

      await refreshBalance();
      return tradeId;
    } catch (e) {
      _errorMessage = _friendlyError(e);
      debugPrint('❌ depositToEscrow failed: $e');
      return null;
    } finally {
      _setProcessing(false);
    }
  }

  /// Seller confirms energy has been delivered.
  Future<bool> confirmDelivery(String tradeId, String supabaseRequestId) async {
    return _callContractVoid(
      functionName: 'confirmDelivery',
      args: [_hexToBytes32(tradeId)],
      requestId: supabaseRequestId,
      action: 'confirmDelivery',
    );
  }

  /// Buyer confirms receipt — triggers automatic payment to seller.
  Future<bool> confirmReceipt(String tradeId, String supabaseRequestId) async {
    return _callContractVoid(
      functionName: 'confirmReceipt',
      args: [_hexToBytes32(tradeId)],
      requestId: supabaseRequestId,
      action: 'confirmReceipt',
    );
  }

  /// Either party raises a dispute.
  Future<bool> raiseDispute(String tradeId, String supabaseRequestId) async {
    return _callContractVoid(
      functionName: 'raiseDispute',
      args: [_hexToBytes32(tradeId)],
      requestId: supabaseRequestId,
      action: 'raiseDispute',
    );
  }

  /// Buyer claims refund after timeout.
  Future<bool> claimRefund(String tradeId, String supabaseRequestId) async {
    return _callContractVoid(
      functionName: 'refund',
      args: [_hexToBytes32(tradeId)],
      requestId: supabaseRequestId,
      action: 'refund',
    );
  }

  // ── On-chain status query ──────────────────────────────────────────────────

  /// Reads current trade status directly from the contract.
  Future<EscrowStatus?> getTradeStatus(String tradeId) async {
    if (_contract == null) return null;
    try {
      final client = Web3Client(WalletService.rpcUrl, http.Client());
      final result = await client.call(
        contract: _contract!,
        function: _fn('getTradeStatus'),
        params: [_hexToBytes32(tradeId)],
      );
      client.dispose();
      if (result.isEmpty) return null;
      return _statusFromInt((result[0] as BigInt).toInt());
    } catch (e) {
      debugPrint('❌ getTradeStatus failed: $e');
      return null;
    }
  }

  // ── Private helpers ────────────────────────────────────────────────────────

  Future<bool> _callContractVoid({
    required String functionName,
    required List<dynamic> args,
    required String requestId,
    required String action,
  }) async {
    if (!_assertReady()) return false;
    _setProcessing(true);
    try {
      final data = _fn(functionName).encodeCall(args);

      final txHash = await _wallet.sendTransaction(
        toAddress: WalletService.contractAddress,
        valueWei: BigInt.zero,
        data: Uint8List.fromList(data),
      );

      final receipt = await _wallet.waitForReceipt(txHash);
      if (receipt == null || !receipt.status!) {
        throw Exception('Transaction reverted');
      }

      await _recordTxInSupabase(
        requestId: requestId,
        txHash: txHash,
        tradeId: null,
        action: action,
        amountPol: 0,
      );

      await refreshBalance();
      notifyListeners();
      return true;
    } catch (e) {
      _errorMessage = _friendlyError(e);
      debugPrint('❌ $functionName failed: $e');
      return false;
    } finally {
      _setProcessing(false);
    }
  }

  Future<void> _recordTxInSupabase({
    required String requestId,
    required String txHash,
    required String? tradeId,
    required String action,
    required double amountPol,
  }) async {
    try {
      await _supabase.from('blockchain_transactions').upsert({
        'request_id': requestId,
        'tx_hash': txHash,
        'trade_id': tradeId,
        'action': action,
        'amount_pol': amountPol,
        'wallet_address': _walletAddress,
        'chain_id': WalletService.chainId,
        'created_at': DateTime.now().toIso8601String(),
      });
      debugPrint('✅ Tx recorded in Supabase: $txHash');
    } catch (e) {
      // Non-fatal — the on-chain tx already succeeded
      debugPrint('⚠️ Could not record tx in Supabase: $e');
    }
  }

  String? _extractTradeIdFromReceipt(TransactionReceipt receipt) {
    // TradeCreated event: first indexed topic after the event signature is tradeId
    try {
      if (receipt.logs.isEmpty) return null;
      final log = receipt.logs.first;
      if (log.topics == null || log.topics!.length < 2) return null;
      return log.topics![1]; // tradeId is first indexed param
    } catch (_) {
      return null;
    }
  }

  /// Converts a hex string (0x...) to Uint8List bytes32
  Uint8List _hexToBytes32(String hex) {
    final clean = hex.startsWith('0x') ? hex.substring(2) : hex;
    final padded = clean.padLeft(64, '0');
    return Uint8List.fromList(
      List.generate(32, (i) => int.parse(padded.substring(i * 2, i * 2 + 2), radix: 16)),
    );
  }

  bool _assertReady() {
    if (!walletReady) {
      _errorMessage = 'Wallet not initialized. Please wait.';
      notifyListeners();
      return false;
    }
    if (_contract == null) {
      _errorMessage = 'Contract not deployed yet.';
      notifyListeners();
      return false;
    }
    return true;
  }

  void _setProcessing(bool v) {
    _isProcessing = v;
    if (!v) _errorMessage = null;
    notifyListeners();
  }

  String _friendlyError(Object e) {
    final msg = e.toString();
    if (msg.contains('insufficient funds')) {
      return 'Insufficient POL balance. Please top up your wallet.';
    }
    if (msg.contains('user rejected')) return 'Transaction cancelled.';
    if (msg.contains('nonce')) return 'Transaction conflict — please retry.';
    if (msg.contains('revert')) {
      if (msg.contains('Only buyer')) return 'Only the buyer can do this.';
      if (msg.contains('Only seller')) return 'Only the seller can do this.';
      if (msg.contains('Timeout not yet')) return 'The 48-hour timeout has not elapsed yet.';
      if (msg.contains('Dispute window')) return 'The dispute window has closed.';
      return 'Contract rejected the transaction: $msg';
    }
    return 'Transaction failed. Please try again.';
  }


  // ── Plain POL transfer ────────────────────────────────────────────────────────

  /// Sends POL directly from this wallet to any address.
  /// No smart contract involved — plain wallet-to-wallet transfer.
  /// Used for: funding testers, sending to friends, topping up devices.
  Future<String?> sendMatic({
    required String toAddress,
    required double amount,
  }) async {
    if (!_assertReady()) return null;

    if (amount <= 0) {
      _errorMessage = 'Amount must be greater than 0.';
      notifyListeners();
      return null;
    }

    if (amount > _polBalance) {
      _errorMessage = 'Insufficient balance.';
      notifyListeners();
      return null;
    }

    _setProcessing(true);
    try {
      // Convert POL to wei (1 POL = 10^18 wei)
      final valueWei = BigInt.from((amount * 1e18).round());

      final txHash = await _wallet.sendTransaction(
        toAddress: toAddress,
        valueWei: valueWei,
        data: Uint8List(0), // empty = plain transfer, no contract call
      );

      debugPrint('✅ Sent $amount POL to $toAddress — tx: $txHash');

      // Wait for confirmation then refresh balance
      await _wallet.waitForReceipt(txHash);
      await refreshBalance();

      return txHash;
    } catch (e) {
      _errorMessage = _friendlyError(e);
      debugPrint('❌ sendMatic failed: $e');
      return null;
    } finally {
      _setProcessing(false);
    }
  }

  // ── Balance polling ────────────────────────────────────────────────────────

  /// Polls the Polygon RPC for the current balance every 30 seconds.
  /// This ensures the UI stays up to date when:
  ///   - Someone sends POL to this wallet
  ///   - An escrow contract releases funds
  ///   - Any external transaction affects the balance
  void _startBalancePolling() {
    _balancePollTimer?.cancel();
    // Fetch ZAR rate immediately on first connect
    _fetchZarRate();
    _balancePollTimer = Timer.periodic(
      const Duration(seconds: 30),
      (_) async {
        if (!walletReady) return;
        // Refresh balance
        try {
          final fresh = await _wallet.getBalance();
          if (fresh != _polBalance) {
            _polBalance = fresh;
            debugPrint('💰 Balance updated: $_polBalance POL');
            notifyListeners();
          }
        } catch (e) {
          debugPrint('⚠️  Balance poll failed (will retry): $e');
        }
        // Refresh ZAR rate every 5 minutes (every 10th 30s tick)
        if (DateTime.now().minute % 5 == 0) _fetchZarRate();
      },
    );
    debugPrint('⏱️  Balance polling started (every 30s)');
  }

  Future<void> _fetchZarRate() async {
    try {
      final uri = Uri.parse(
        'https://api.coingecko.com/api/v3/simple/price'
        '?ids=polygon-ecosystem-token&vs_currencies=zar',
      );
      final response = await http
          .get(uri, headers: {'Accept': 'application/json'})
          .timeout(const Duration(seconds: 8));
      if (response.statusCode == 200) {
        final data = jsonDecode(response.body);
        final rate =
            (data['polygon-ecosystem-token']?['zar'] as num?)?.toDouble();
        if (rate != null && rate != _polToZarRate) {
          _polToZarRate = rate;
          debugPrint('💱 POL/ZAR rate updated: $rate');
          notifyListeners();
        }
      }
    } catch (e) {
      debugPrint('⚠️  ZAR rate fetch failed: $e');
    }
  }

  void _stopBalancePolling() {
    _balancePollTimer?.cancel();
    _balancePollTimer = null;
  }

  @override
  void dispose() {
    _stopBalancePolling();
    super.dispose();
  }

  void clearError() {
    _errorMessage = null;
    notifyListeners();
  }
}